import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export const generateOrderPDF = (order) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;

    // --- Header ---
    // Logo
    const logoUrl = '/logo.jpeg';
    const logoImg = new Image();
    logoImg.src = logoUrl;

    logoImg.onload = () => {
        // Draw Logo
        doc.addImage(logoImg, 'JPEG', 15, 15, 25, 25);

        // Company Name
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text('BARAKA', 45, 25);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text('Order Management System', 45, 32);

        // Order Details (Right side)
        doc.setFontSize(10);
        doc.text(`Order #: ${order.order_number}`, pageWidth - 15, 20, { align: 'right' });
        doc.text(`Date: ${new Date(order.created_at).toLocaleDateString()}`, pageWidth - 15, 26, { align: 'right' });

        // --- Order Items Table ---
        const tableStartY = 50;

        const tableBody = order.order_items.map(item => [
            item.product_name,
            item.quantity,
            item.notes || '-'
        ]);

        autoTable(doc, {
            startY: tableStartY,
            head: [['Product Name', 'Quantity', 'Notes']],
            body: tableBody,
            theme: 'grid',
            headStyles: { fillColor: [0, 0, 0], textColor: 255, fontStyle: 'bold' }, // Black header
            styles: { fontSize: 10, cellPadding: 3 },
            columnStyles: {
                0: { cellWidth: 'auto' }, // Product Name
                1: { cellWidth: 30, halign: 'center' }, // Quantity
                2: { cellWidth: 60 } // Notes
            },
        });

        // --- Footer ---
        const finalY = doc.lastAutoTable.finalY || tableStartY;

        doc.setFontSize(8);
        doc.setTextColor(100);
        doc.text('Generated by Baraka Admin System', pageWidth / 2, 280, { align: 'center' });

        // Save
        doc.save(`Order_${order.order_number}.pdf`);
    };

    logoImg.onerror = () => {
        // Fallback if logo fails to load
        console.warn('Logo failed to load, generating PDF without logo');

        // Company Name (No Logo)
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text('BARAKA', 15, 25);

        // Order Details
        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text(`Order #: ${order.order_number}`, pageWidth - 15, 20, { align: 'right' });
        doc.text(`Date: ${new Date(order.created_at).toLocaleDateString()}`, pageWidth - 15, 26, { align: 'right' });

        // Table
        const tableBody = order.order_items.map(item => [
            item.product_name,
            item.quantity,
            item.notes || '-'
        ]);

        autoTable(doc, {
            startY: 40,
            head: [['Product Name', 'Quantity', 'Notes']],
            body: tableBody,
            theme: 'grid',
            headStyles: { fillColor: [0, 0, 0], textColor: 255, fontStyle: 'bold' },
        });

        doc.save(`Order_${order.order_number}.pdf`);
    };
};
